name: Build .NET Core App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Test dotnet
      run: dotnet test --verbosity normal

    - name: Execute dotnet
      run: dotnet build

    - name: Create npm lockfile
      run: npm i --package-lock-only

    - name: npm audit fix
      run: npm audit fix

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-core-angular-artifact
        path: bin/Release/dotnet-core-angular.1.0.0.nupkg
