name: Build .NET Core App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4

    - name: Restore dependencies
      run: dotnet restore

    - name: Test dotnet
      run: dotnet test --verbosity normal

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: szymmirr/dotnet-core-angular

    - name: Execute dotnet
      run: dotnet build

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-core-angular-artifact
        path: bin/Release/dotnet-core-angular.1.0.0.nupkg
